/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Nov 9 2021
 * Processor: STM32F103T6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <stdio.h>
#include <stdint.h>
#include "lcd.h"
#include "rlc.h"

void usart1_init(void);
void usart1_sendByte(unsigned char c);
void usart1_sendInt(unsigned int i);

volatile 	uint32_t L2=0,aux;

int main (void)
{ 
	/*
   RCC->APB2ENR |= 0xFC | (1<<9); // enable clocks for GPIO and ADC1
   GPIOA->CRL = 0x44444004; //PA1 and PA2 as analog input
   ADC1->CR2 = 1 //ADON = 1 (power-up)
	*/


	RCC->APB2ENR |= (0xFC| (1<<14)); /* enable GPIO clocks and USART1 clock */
	RCC->APB1ENR |= (1<<0); /* enable TIM2 clock */


	GPIOB->CRL = 0x44444443;
	GPIOA->CRL = 0x44444844; /* PA2 (TIM2 CH3): input pull-up */
	GPIOA->ODR |= (1<<2);

	TIM2->CCMR2 = 0x001; /* Pin TIM2_CH3 as input for channel 3 */
	TIM2->CCER = (0x1<< 8); /*CC3P = 0 (rising), CC3E = 1 */
	TIM2->PSC = 7200-1;
	TIM2->ARR = 50000-1;
	usart1_init();
	lcd_init();
	lcd_gotoXY(0,0);

while(1) {
	L2 = 1000000.0*RLC_measure();
	aux = L2;
	while (L2 > 0){
		aux = L2%10;
		L2/= 10;
		lcd_sendData(aux + '0');
	}
	 /* send the difference */
	//usart1_sendInt((uint32_t) L);
	//usart1_sendByte('\n'); /* go to new line */
	//usart1_sendByte('\r');

	}

}   

void usart1_init( ) {
	GPIOA->ODR |= (1<<10); //pull-up PA10
	GPIOA->CRH = 0x444448B4; // RX1=input with pull-up, TX1=alt. func output
	USART1->CR1 = 0x200C;
	USART1->BRR = 104; // 72MHz/9600bps = 7500
}
void usart1_sendByte(unsigned char c) {
	while((USART1->SR&(1<<6)) == 0); //wait until the TC flag is set
	USART1->DR = c;
}

void usart1_sendStr(char *str) {
	while(*str != 0) {
	usart1_sendByte(*str);
	str++;
	}
}
/* The function sends a number through USART1 */
void usart1_sendInt(unsigned int i) {
	char str[10];
	sprintf(str,"%d",i);
	usart1_sendStr(str);
}

