/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Nov 9 2021
 * Processor: STM32F103T6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <stdio.h>
#include <stdint.h>
#include "lcd.h"
#include "rlc.h"


volatile 	uint32_t L2=0,aux,j;

int main (void)
{ 

	RCC->APB2ENR |= (0xFC| (1<<14)); /* enable GPIO clocks and USART1 clock */
	RCC->APB1ENR |= (1<<0); /* enable TIM2 clock */

	RLC_init();
	lcd_init();
	

while(1) {
	L2 = 1000000.0*RLC_measure();
	aux = L2;
	//j=0;
	//lcd_gotoXY(6,0);
	//while ((L2 > 0) & (j < 3)){
		//aux = L2%10;
		//L2/= 10;
		//lcd_sendData(aux + '0');
		//j++;
	//}

	 /* send the difference */
	//usart1_sendInt((uint32_t) L);
	//usart1_sendByte('\n'); /* go to new line */
	//usart1_sendByte('\r');

	//delay_us(5000);

	}

}   


